"""HTML formatting utilities for candidate feedback - fallback only."""
import re
from models.feedback_models import CandidateFeedback

# Mandatory signature that will be added to all emails
EMAIL_SIGNATURE = """<p style="margin-top: 30px;">
    Z wyrazami szacunku<br><br>
    <strong>Dział HR</strong>
</p>"""

# Mandatory footer that will be added to all feedback emails
AI_FOOTER = """<p style="font-size: 10px; color: #666; margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; text-align: center;">
    Informacja ta została wygenerowana automatycznie przez Asystenta AI działu rekrutacji, jednakże decyzje dotyczące zatrudnienia zostały podjęte przez pracownika działu HR.
</p>"""

# Mandatory consent messages (hardcoded, not generated by AI)
CONSENT_MESSAGE_NO = """<p style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #667eea; border-radius: 4px;">
    <strong>Informacja dotycząca innych stanowisk:</strong><br>
    Zauważyliśmy, że nie mamy Twojej zgody na rozważanie pod względem innych stanowisk. Jeżeli chciałbyś to zmienić, proszę odpowiedz na tego maila z informacją, że wyrażasz zgodę.
</p>"""

CONSENT_MESSAGE_YES = """<p style="margin-top: 20px; padding: 15px; background-color: #f0f9ff; border-left: 4px solid #4caf50; border-radius: 4px;">
    <strong>Informacja dotycząca innych stanowisk:</strong><br>
    Zauważyliśmy, że wyraziłeś zgodę na branie pod uwagę do innych stanowisk. Dlatego gdy znajdziemy odpowiednią dla Ciebie ofertę, niezwłocznie się odezwiemy. Natomiast jeżeli chciałbyś zmienić zdanie, proszę poinformuj nas o tym odpowiadając na tego maila.
</p>"""


def format_feedback_as_html(feedback: CandidateFeedback, consent_for_other_positions: bool = False) -> str:
    """
    Get HTML formatted version of feedback.
    Adds mandatory AI footer and consent message (HARDCODED, not generated by AI) before closing </body> tag.
    
    Args:
        feedback: CandidateFeedback object
        consent_for_other_positions: Optional boolean indicating if candidate consented to other positions
        
    Returns:
        HTML formatted string ready for email with mandatory footer and consent message (both hardcoded)
    """
    # html_content is generated by AI - we only add hardcoded footer and consent message
    if hasattr(feedback, 'html_content') and feedback.html_content:
        html_content = feedback.html_content
    
        # Add hardcoded consent message before footer
        # These messages are NOT generated by AI - they are hardcoded constants
        consent_message = ""
        if consent_for_other_positions is True:
            consent_message = CONSENT_MESSAGE_YES
        else:
            consent_message = CONSENT_MESSAGE_NO
        
        # Add hardcoded signature, consent message, and footer before closing </body> tag
        # Check if footer already exists (to avoid duplicates)
        if "Informacja ta została wygenerowana automatycznie" not in html_content:
            # Insert hardcoded signature, consent message (if any), and hardcoded footer before </body> tag
            html_content = re.sub(
                r'(</body>)',
                EMAIL_SIGNATURE + consent_message + AI_FOOTER + r'\1',
                html_content,
                flags=re.IGNORECASE
            )
        
        return html_content
    
    # Fallback: very basic HTML (should rarely be used)
    return f"""<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Odpowiedź na aplikację</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <p>Dzień dobry,</p>
    <p>Dziękujemy za aplikację. Została ona przeanalizowana przez nasz zespół.</p>
    <p>Z poważaniem,<br>Zespół HR</p>
{AI_FOOTER}
</body>
</html>"""

